/* eslint-disable */
// Generated by database-validator-generator. Do not edit by hand.
// PostgreSQL schema: public

import { z } from "zod";

/**
 * Projects owned by users.
 * @typedef {object} Projects
 * @property {number} id
 * @property {number} owner_id
 * @property {string} title
 * @property {Date} created_at
 */
export const projectsRowSchema = z.object({
  id: z.number().int().gte(-2147483648).lte(2147483647),
  owner_id: z.number().int().gte(-2147483648).lte(2147483647),
  title: z.string().min(1).max(120),
  created_at: z.coerce.date(),
}).describe("Projects owned by users.");
export const projectsSchema = projectsRowSchema;
export const projectsInsertSchema = z.object({
  owner_id: z.number().int().gte(-2147483648).lte(2147483647),
  title: z.string().min(1).max(120),
  created_at: z.coerce.date().optional(),
}).describe("Insert shape for Projects owned by users.");
export const projectsUpdateSchema = z.object({
  owner_id: z.number().int().gte(-2147483648).lte(2147483647).optional(),
  title: z.string().min(1).max(120).optional(),
  created_at: z.coerce.date().optional(),
}).describe("Update shape for Projects owned by users.");

/**
 * Project tasks.
 * @typedef {object} Tasks
 * @property {number} id
 * @property {number} project_id
 * @property {string} title
 * @property {"todo" | "doing" | "done"} status
 * @property {Array<string>} tags
 * @property {Date | null} due_on
 */
export const tasksRowSchema = z.object({
  id: z.number().int().gte(-2147483648).lte(2147483647),
  project_id: z.number().int().gte(-2147483648).lte(2147483647),
  title: z.string().min(3).max(140),
  status: z.enum(["todo", "doing", "done"]),
  tags: z.array(z.string()).max(5),
  due_on: z.coerce.date().nullable(),
}).describe("Project tasks.");
export const tasksSchema = tasksRowSchema;
export const tasksInsertSchema = z.object({
  project_id: z.number().int().gte(-2147483648).lte(2147483647),
  title: z.string().min(3).max(140),
  status: z.enum(["todo", "doing", "done"]).optional(),
  tags: z.array(z.string()).max(5).optional(),
  due_on: z.coerce.date().nullable().optional(),
}).describe("Insert shape for Project tasks.");
export const tasksUpdateSchema = z.object({
  project_id: z.number().int().gte(-2147483648).lte(2147483647).optional(),
  title: z.string().min(3).max(140).optional(),
  status: z.enum(["todo", "doing", "done"]).optional(),
  tags: z.array(z.string()).max(5).optional(),
  due_on: z.coerce.date().nullable().optional(),
}).describe("Update shape for Project tasks.");

/**
 * People who own projects.
 * @typedef {object} Users
 * @property {number} id
 * @property {string} email - Login email. @format email
 * @property {string} name
 * @property {Date} created_at
 */
export const usersRowSchema = z.object({
  id: z.number().int().gte(-2147483648).lte(2147483647),
  email: z.string().email().max(320).describe("Login email. @format email"),
  name: z.string().min(2).max(80),
  created_at: z.coerce.date(),
}).describe("People who own projects.");
export const usersSchema = usersRowSchema;
export const usersInsertSchema = z.object({
  email: z.string().email().max(320).describe("Login email. @format email"),
  name: z.string().min(2).max(80),
  created_at: z.coerce.date().optional(),
}).describe("Insert shape for People who own projects.");
export const usersUpdateSchema = z.object({
  email: z.string().email().max(320).describe("Login email. @format email").optional(),
  name: z.string().min(2).max(80).optional(),
  created_at: z.coerce.date().optional(),
}).describe("Update shape for People who own projects.");

export const schemas = {
  projects: projectsSchema,
  tasks: tasksSchema,
  users: usersSchema,
};

export const rowSchemas = {
  projects: projectsRowSchema,
  tasks: tasksRowSchema,
  users: usersRowSchema,
};

export const insertSchemas = {
  projects: projectsInsertSchema,
  tasks: tasksInsertSchema,
  users: usersInsertSchema,
};

export const updateSchemas = {
  projects: projectsUpdateSchema,
  tasks: tasksUpdateSchema,
  users: usersUpdateSchema,
};

export const metadata = {
  "projects": {
    "description": "Projects owned by users.",
    "primaryKey": [
      "id"
    ],
    "unique": [],
    "foreignKeys": [
      {
        "name": "projects_owner_id_fkey",
        "columns": [
          "owner_id"
        ],
        "definition": "FOREIGN KEY (owner_id) REFERENCES users(id) ON DELETE CASCADE",
        "description": null,
        "foreignSchema": "public",
        "foreignTable": "users",
        "foreignColumns": [
          "id"
        ]
      }
    ],
    "exclusionConstraints": [],
    "constraints": [
      {
        "name": "projects_owner_id_fkey",
        "columns": [
          "owner_id"
        ],
        "definition": "FOREIGN KEY (owner_id) REFERENCES users(id) ON DELETE CASCADE",
        "description": null,
        "type": "f"
      },
      {
        "name": "projects_pkey",
        "columns": [
          "id"
        ],
        "definition": "PRIMARY KEY (id)",
        "description": null,
        "type": "p"
      }
    ],
    "columns": {
      "id": {
        "description": null,
        "nullable": false,
        "dataType": "integer",
        "udtSchema": "pg_catalog",
        "udtName": "int4",
        "domainSchema": null,
        "domainName": null,
        "default": null,
        "identity": "ALWAYS",
        "generated": null,
        "primaryKey": true,
        "checks": []
      },
      "owner_id": {
        "description": null,
        "nullable": false,
        "dataType": "integer",
        "udtSchema": "pg_catalog",
        "udtName": "int4",
        "domainSchema": null,
        "domainName": null,
        "default": null,
        "identity": null,
        "generated": null,
        "primaryKey": false,
        "checks": []
      },
      "title": {
        "description": null,
        "nullable": false,
        "dataType": "character varying",
        "udtSchema": "pg_catalog",
        "udtName": "varchar",
        "domainSchema": null,
        "domainName": null,
        "default": null,
        "identity": null,
        "generated": null,
        "primaryKey": false,
        "checks": [
          {
            "name": "projects_title_check",
            "definition": "CHECK (title::text <> ''::text)",
            "description": null
          }
        ]
      },
      "created_at": {
        "description": null,
        "nullable": false,
        "dataType": "timestamp with time zone",
        "udtSchema": "pg_catalog",
        "udtName": "timestamptz",
        "domainSchema": null,
        "domainName": null,
        "default": "now()",
        "identity": null,
        "generated": null,
        "primaryKey": false,
        "checks": []
      }
    }
  },
  "tasks": {
    "description": "Project tasks.",
    "primaryKey": [
      "id"
    ],
    "unique": [],
    "foreignKeys": [
      {
        "name": "tasks_project_id_fkey",
        "columns": [
          "project_id"
        ],
        "definition": "FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE CASCADE",
        "description": null,
        "foreignSchema": "public",
        "foreignTable": "projects",
        "foreignColumns": [
          "id"
        ]
      }
    ],
    "exclusionConstraints": [],
    "constraints": [
      {
        "name": "tasks_pkey",
        "columns": [
          "id"
        ],
        "definition": "PRIMARY KEY (id)",
        "description": null,
        "type": "p"
      },
      {
        "name": "tasks_project_id_fkey",
        "columns": [
          "project_id"
        ],
        "definition": "FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE CASCADE",
        "description": null,
        "type": "f"
      }
    ],
    "columns": {
      "id": {
        "description": null,
        "nullable": false,
        "dataType": "integer",
        "udtSchema": "pg_catalog",
        "udtName": "int4",
        "domainSchema": null,
        "domainName": null,
        "default": null,
        "identity": "ALWAYS",
        "generated": null,
        "primaryKey": true,
        "checks": []
      },
      "project_id": {
        "description": null,
        "nullable": false,
        "dataType": "integer",
        "udtSchema": "pg_catalog",
        "udtName": "int4",
        "domainSchema": null,
        "domainName": null,
        "default": null,
        "identity": null,
        "generated": null,
        "primaryKey": false,
        "checks": []
      },
      "title": {
        "description": null,
        "nullable": false,
        "dataType": "character varying",
        "udtSchema": "pg_catalog",
        "udtName": "varchar",
        "domainSchema": null,
        "domainName": null,
        "default": null,
        "identity": null,
        "generated": null,
        "primaryKey": false,
        "checks": [
          {
            "name": "tasks_title_check",
            "definition": "CHECK (char_length(title::text) >= 3)",
            "description": null
          }
        ]
      },
      "status": {
        "description": null,
        "nullable": false,
        "dataType": "USER-DEFINED",
        "udtSchema": "public",
        "udtName": "task_status",
        "domainSchema": null,
        "domainName": null,
        "default": "'todo'::task_status",
        "identity": null,
        "generated": null,
        "primaryKey": false,
        "checks": []
      },
      "tags": {
        "description": null,
        "nullable": false,
        "dataType": "ARRAY",
        "udtSchema": "pg_catalog",
        "udtName": "_text",
        "domainSchema": null,
        "domainName": null,
        "default": "'{}'::text[]",
        "identity": null,
        "generated": null,
        "primaryKey": false,
        "checks": [
          {
            "name": "tasks_tags_check",
            "definition": "CHECK (array_length(tags, 1) <= 5 OR array_length(tags, 1) IS NULL)",
            "description": null
          }
        ]
      },
      "due_on": {
        "description": null,
        "nullable": true,
        "dataType": "date",
        "udtSchema": "pg_catalog",
        "udtName": "date",
        "domainSchema": null,
        "domainName": null,
        "default": null,
        "identity": null,
        "generated": null,
        "primaryKey": false,
        "checks": []
      }
    }
  },
  "users": {
    "description": "People who own projects.",
    "primaryKey": [
      "id"
    ],
    "unique": [
      {
        "name": "users_email_key",
        "columns": [
          "email"
        ],
        "definition": "UNIQUE (email)",
        "description": null
      }
    ],
    "foreignKeys": [],
    "exclusionConstraints": [],
    "constraints": [
      {
        "name": "users_email_key",
        "columns": [
          "email"
        ],
        "definition": "UNIQUE (email)",
        "description": null,
        "type": "u"
      },
      {
        "name": "users_pkey",
        "columns": [
          "id"
        ],
        "definition": "PRIMARY KEY (id)",
        "description": null,
        "type": "p"
      }
    ],
    "columns": {
      "id": {
        "description": null,
        "nullable": false,
        "dataType": "integer",
        "udtSchema": "pg_catalog",
        "udtName": "int4",
        "domainSchema": null,
        "domainName": null,
        "default": null,
        "identity": "ALWAYS",
        "generated": null,
        "primaryKey": true,
        "checks": []
      },
      "email": {
        "description": "Login email. @format email",
        "nullable": false,
        "dataType": "character varying",
        "udtSchema": "pg_catalog",
        "udtName": "varchar",
        "domainSchema": null,
        "domainName": null,
        "default": null,
        "identity": null,
        "generated": null,
        "primaryKey": false,
        "checks": []
      },
      "name": {
        "description": null,
        "nullable": false,
        "dataType": "character varying",
        "udtSchema": "pg_catalog",
        "udtName": "varchar",
        "domainSchema": null,
        "domainName": null,
        "default": null,
        "identity": null,
        "generated": null,
        "primaryKey": false,
        "checks": [
          {
            "name": "users_name_check",
            "definition": "CHECK (char_length(name::text) >= 2)",
            "description": null
          }
        ]
      },
      "created_at": {
        "description": null,
        "nullable": false,
        "dataType": "timestamp with time zone",
        "udtSchema": "pg_catalog",
        "udtName": "timestamptz",
        "domainSchema": null,
        "domainName": null,
        "default": "now()",
        "identity": null,
        "generated": null,
        "primaryKey": false,
        "checks": []
      }
    }
  }
};

